version: '3.7'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    command: flask run --host 0.0.0.0
    environment:
      - EASYPOST_API_KEY=[YOUR_EASYPOST_API_KEY]
      - LOB_API_KEY=[YOUR_LOB_API_KEY]
      - AWS_ACCESS_KEY=[YOUR_AWS_ACCESS_KEY]
      - AWS_SECRET_KEY=[YOUR_AWS_SECRET_KEY]
      - SENTRY_DSN=[YOUR_SENTRY_DSN]
      - SMARTY_STREETS_AUTH_ID=[YOUR_SMARTY_STREETS_AUTH_ID]
      - SMARTY_STREETS_AUTH_TOKEN=[YOUR_SMARTY_STREETS_AUTH_TOKEN]
      - DEBUG_SUBMIT=TRUE
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - db

  worker:
    build: .
    command: flask rq worker
    environment:
      - FLASK_APP=app/wsgi.py
      - AWS_ACCESS_KEY=[YOUR_AWS_ACCESS_KEY]
      - AWS_SECRET_KEY=[YOUR_AWS_SECRET_KEY]
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - db

  redis:
    image: redis:3-alpine

  db:
    image: postgres:10.7-alpine
    environment:
      - POSTGRES_PASSWORD=[POSTGRES_PASSWORD]
      - POSTGRES_USER=postgres
      - POSTGRES_DB=votebot-forms
